apiversion: apps/v1
kind: Deployment
metadata:
  name: sampledep
  labels:
    app: samplekube
spec:
  selector:
    matchLabels:
      app: samplekube
  replicas: 3
  template:
    metadata:
    name: samplepod
    labels:
      app: samplekube
      spec:
        containers:
          - name: samplecontainer
            image: httpd
            ports:
              - containerPort: 80

