apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledep
spec:
  selector:
    matchLabels:
      app: samplekube
  replicas: 3
  template:
    metadata:
      labels:
         app: samplekube
    spec:
      containers:
        - name: samplecontainer
          image: httpd
          ports:
          - containerPort: 80

